@startuml TelemetryService

title Telemetry Service Component Diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(APIGateway, "API Gateway", "Nginx")

ComponentDb(TelemetryDB, "Telemetry DB", "MongoDB", "Хранение показаний устройств")

ContainerQueue(TelemetryDataQueue, "Telemetry Data Queue", "Kafka")

Container_Boundary(TelemetryService, "Сервис сбора и анализа данных от устройств") {
    Component(TelemetryController, "Telemetry Controller", "", "Обработка внешних запросов")
    Component(EventListener, "Event Listener", "", "Обрабатывает события из Kafka")
    Component(TelemetryProcessor, "Telemetry Processor", "", "Обработка и запись данных")
    Component(TelemetryRepository, "Telemetry Repository", "", "Слой доступа к данным")
}

Rel(APIGateway, TelemetryController, "REST API вызовы", "HTTPS")

Rel(TelemetryRepository, TelemetryDB, "Читает и записывает данные", "MongoDB Driver")

Rel(EventListener, TelemetryProcessor, "Передача данных для агрегации и сохранения")

Rel(TelemetryProcessor, TelemetryDB, "Сохранения агрегированных данных")
Rel(TelemetryProcessor, TelemetryDataQueue, "aggregated_telemetry_report")

Rel(TelemetryController, TelemetryRepository, "Получение данных по запросу")

Rel(TelemetryDataQueue, EventListener, "telemetry_data_received")
