@startuml UserService

title User Service Component Diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(APIGateway, "API Gateway", "Nginx")

ComponentDb(UserDB, "User DB", "PostgreSQL", "Учетные записи пользователей, права доступа")

Container_Boundary(UserService, "Сервис пользователей") {
    Component(UserController, "User Controller", "", "Обработка внешних запросов")
    Component(UserManager, "User Manager", "", "Управление учетными записями пользователей")
    Component(AuthenticationService, "AuthenticationService", "", "Аутентификация пользователей")
    Component(AuthorizationModule, "Authorization Module", "", "Контроль доступа")
    Component(UserProfileManager, "User Profile Manager", "", "Управление профилями")
    Component(UserRepository, "UserRepository", "", "Слой доступа к данным")
}

Rel(APIGateway, UserController, "REST API вызовы", "HTTPS")

Rel(UserRepository, UserDB, "Читает и записывает данные", "JDBC")

Rel(UserController, UserManager, "Регистрация нового пользователя")
Rel(UserController, AuthorizationModule, "Проверка доступа пользователя")
Rel(UserController, UserProfileManager, "Изменение профиля")

Rel(UserManager, AuthenticationService, "Генерация токена")
Rel(UserManager, UserRepository, "Сохранение учетных записей")

Rel(UserProfileManager, UserRepository, "Сохранение изменений профиля")

Rel(AuthenticationService, UserRepository, "Получение информации о пользователе")

Rel(AuthorizationModule, UserRepository, "Данные о пользователе и его правах")
